# SOURCE THIS FILE BEFORE LAUNCHING NODES FROM THIS PACKAGE
#
# TO RUN THE SYSTEM FULLY ON THE LOCAL COMPUTER:
export ROS_MASTER_URI=http://localhost:11311
# TO RUN THE SYSTEM AS ON A DEFAULT CONFIGURATION OF THE NETWROK:
#export ROS_MASTER_URI=http://dfallmaster:11311
# TO RUN THE SYSTEM AS A ROS-MASTER ON A DEFAULT CONFIGURATION OF THE NETWROK:
#export ROS_HOSTNAME=dfallmaster
#
# OTHER NECESSARY ROS ENVIRONMENT VARIABLES:
export ROS_IP=$(hostname -I | awk '{print $1;}')
export ROS_NAMESPACE='asclinic'
#
# OTHER PACKAGE SPECIFIC ENVIRONMENT VARIABLES:
# <none at this stage>
